service: rust-lambda
frameworkVersion: '3'
configValidationMode: error
useDotenv: true

provider:
  name: aws
  memorySize: 128
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
          Resource: '*'

  environment:
    ENVIRONMENT: ${opt:stage, 'local'}

package:
  individually: true

functions:
  rust:
    handler: functions/api.api
    runtime: provided.al2
    tags:
      rust: true
    events:
      - http:
          method: post
          path: hello
          cors: true

custom:
  # localstack
  localstack:
    stages:
      - local
    # host: http://0.0.0.0

plugins:
  - sls-rust
  - serverless-localstack
